'use strict';
const VERSION='0.9.0';
const KEY='blueatlas-alpha-081';
const species=[
{id:'saupe',name:'Saupe',latin:'Sarpa salpa',group:'Poisson',habitat:'Herbier / roche',prob:95,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Sarpa_salpa_1.jpg/640px-Sarpa_salpa_1.jpg',desc:'Poisson argenté parcouru de fines lignes dorées, souvent en banc près des herbiers.'},
{id:'girelle',name:'Girelle commune',latin:'Coris julis',group:'Poisson',habitat:'Roche / herbier',prob:95,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Coris_julis_male.jpg/640px-Coris_julis_male.jpg',desc:'Petite girelle très vive, aux couleurs variables selon le sexe et l’âge.'},
{id:'sar',name:'Sar commun',latin:'Diplodus sargus',group:'Poisson',habitat:'Roche',prob:90,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Diplodus_sargus.jpg/640px-Diplodus_sargus.jpg',desc:'Poisson argenté à bandes sombres, fréquent sur les petits fonds rocheux.'},
{id:'oblade',name:'Oblade',latin:'Oblada melanura',group:'Poisson',habitat:'Pleine eau / roche',prob:85,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Oblada_melanura.jpg/640px-Oblada_melanura.jpg',desc:'Poisson argenté reconnaissable à sa tache noire cerclée de blanc près de la queue.'},
{id:'castagnole',name:'Castagnole',latin:'Chromis chromis',group:'Poisson',habitat:'Roche / pleine eau',prob:80,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Chromis_chromis_2.jpg/640px-Chromis_chromis_2.jpg',desc:'Petit poisson sombre nageant en groupes au-dessus des fonds rocheux.'},
{id:'serran',name:'Serran écriture',latin:'Serranus scriba',group:'Poisson',habitat:'Roche / herbier',prob:75,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Serranus_scriba.jpg/640px-Serranus_scriba.jpg',desc:'Poisson territorial coloré, avec des motifs bleus et bruns très caractéristiques.'},
{id:'rouget',name:'Rouget de roche',latin:'Mullus surmuletus',group:'Poisson',habitat:'Sable / roche',prob:65,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Mullus_surmuletus.jpg/640px-Mullus_surmuletus.jpg',desc:'Explore le fond avec ses deux barbillons sensoriels.'},
{id:'poulpe',name:'Poulpe commun',latin:'Octopus vulgaris',group:'Céphalopode',habitat:'Roche',prob:35,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Octopus_vulgaris_2.jpg/640px-Octopus_vulgaris_2.jpg',desc:'Maître du camouflage, souvent caché dans une cavité entourée de coquilles.'},
{id:'murene',name:'Murène méditerranéenne',latin:'Muraena helena',group:'Poisson',habitat:'Faille rocheuse',prob:25,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Muraena_helena_1.jpg/640px-Muraena_helena_1.jpg',desc:'Poisson allongé vivant dans les failles. Observer à distance sans approcher les mains.'},
{id:'seiche',name:'Seiche commune',latin:'Sepia officinalis',group:'Céphalopode',habitat:'Sable / herbier',prob:20,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Sepia_officinalis_%28aquarium%29.jpg/640px-Sepia_officinalis_%28aquarium%29.jpg',desc:'Céphalopode capable de changer rapidement de couleur et de texture.'},
{id:'mero',name:'Mérou brun',latin:'Epinephelus marginatus',group:'Poisson',habitat:'Roche / grotte',prob:12,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Epinephelus_marginatus_1.jpg/640px-Epinephelus_marginatus_1.jpg',desc:'Grand poisson emblématique, plus facile à observer dans les zones protégées.'},
{id:'barracuda',name:'Barracuda méditerranéen',latin:'Sphyraena viridensis',group:'Poisson',habitat:'Pleine eau',prob:10,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Sphyraena_viridensis.jpg/640px-Sphyraena_viridensis.jpg',desc:'Prédateur fuselé parfois visible en banc dans les eaux claires.'},
{id:'oursin',name:'Oursin violet',latin:'Paracentrotus lividus',group:'Échinoderme',habitat:'Roche / herbier',prob:90,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Paracentrotus_lividus_01.jpg/640px-Paracentrotus_lividus_01.jpg',desc:'Oursin fréquent sur les rochers. Ne pas marcher dessus et ne pas le prélever.'},
{id:'etoile',name:'Étoile de mer rouge',latin:'Echinaster sepositus',group:'Échinoderme',habitat:'Roche',prob:20,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Echinaster_sepositus_1.jpg/640px-Echinaster_sepositus_1.jpg',desc:'Étoile rouge vif observée sur les roches ombragées.'},
{id:'concombre',name:'Concombre de mer noir',latin:'Holothuria forskali',group:'Échinoderme',habitat:'Roche / sable',prob:50,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Holothuria_forskali.jpg/640px-Holothuria_forskali.jpg',desc:'Animal benthique allongé participant au recyclage des sédiments.'},
{id:'crabe',name:'Crabe marbré',latin:'Pachygrapsus marmoratus',group:'Crustacé',habitat:'Rochers superficiels',prob:55,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pachygrapsus_marmoratus_2009_G1.jpg/640px-Pachygrapsus_marmoratus_2009_G1.jpg',desc:'Crabe rapide des rochers battus par les vagues, visible tout près de la surface.'}
];
const defaultState=()=>({version:VERSION,expeditions:[],observations:[],activeExpeditionId:null,selectedTab:'home',seenWhatsNew:false});
let state=load();
let modal=null;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.observations){x.selectedTab=x.selectedTab||'home';x.seenWhatsNew=Boolean(x.seenWhatsNew);return x}return defaultState()}catch{return defaultState()}}
function save(){state.version=VERSION;localStorage.setItem(KEY,JSON.stringify(state))}
function uid(p='id'){return p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(x){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}
function duration(exp){const end=exp.endedAt||Date.now();const min=Math.max(0,Math.round((end-exp.startedAt)/60000));return min<60?min+' min':Math.floor(min/60)+' h '+String(min%60).padStart(2,'0')}
function sp(id){return species.find(s=>s.id===id)}
function expObs(id){return state.observations.filter(o=>o.expeditionId===id)}
function discovered(){return new Set(state.observations.filter(o=>o.speciesId&&o.certainty!=='pending').map(o=>o.speciesId))}
function active(){return state.expeditions.find(e=>e.id===state.activeExpeditionId&&!e.endedAt)}
function imageForSpecies(sid){const own=state.observations.find(o=>o.speciesId===sid&&o.photo);return own?.photo||sp(sid)?.img||''}
async function compressFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1280;let w=img.width,h=img.height;if(Math.max(w,h)>max){const q=max/Math.max(w,h);w=Math.round(w*q);h=Math.round(h*q)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.78))};img.src=r.result};r.readAsDataURL(file)})}
function nav(){return `<nav class="nav">${[['home','⌂','Accueil'],['discoveries','◉','Découvertes'],['atlas','◫','Atlas'],['journal','◇','Journal'],['profile','◎','Profil']].map(([id,ic,l])=>`<button data-tab="${id}" class="${state.selectedTab===id?'active':''}"><b>${ic}</b>${l}</button>`).join('')}</nav>`}
function shell(content){return `<main class="app">${content}</main>${nav()}${modal||''}`}
function home(){const d=discovered();const photos=state.observations.filter(o=>o.photo).length;const pending=state.observations.filter(o=>!o.speciesId).length;const last=[...state.expeditions].filter(e=>e.endedAt).sort((a,b)=>b.startedAt-a.startedAt)[0];return shell(`<section class="hero"><div class="brand-row"><div class="brand">BLUE<span>ATLAS</span></div><button class="version-pill" id="versionBtn">Alpha v${VERSION}</button></div><div class="eyebrow">Compagnon d’exploration</div><h1>Bonjour Julien</h1><p class="sub">La mer est magnifique aujourd’hui. Capture maintenant, identifie plus tard.</p><button class="btn block" id="startExp">${active()?'Continuer l’expédition':'Commencer une expédition'}</button></section><div class="stats"><div class="stat"><strong>${d.size}</strong><span>espèces</span></div><div class="stat"><strong>${photos}</strong><span>photos</span></div><div class="stat"><strong>${state.expeditions.length}</strong><span>expéditions</span></div></div>${pending?`<article class="card clickable" data-tab="discoveries"><div class="eyebrow">À faire après la sortie</div><h2>${pending} souvenir${pending>1?'s':''} à identifier</h2><p class="muted">Retrouve tes photos et complète ton Atlas tranquillement.</p></article>`:''}${last?`<div class="section-title"><h2>Dernière aventure</h2><span>Revivre</span></div><article class="card expedition-card clickable" data-open-exp="${last.id}">${expObs(last.id).find(o=>o.photo)?`<img class="expedition-cover" src="${expObs(last.id).find(o=>o.photo).photo}" alt="Couverture de l’expédition">`:''}<div class="expedition-body"><div class="eyebrow">${fmtDate(last.startedAt)}</div><h2>${esc(last.spot||'Corse-du-Sud')}</h2><p class="mini-story">${expObs(last.id).length?`Tu as capturé ${expObs(last.id).length} souvenir${expObs(last.id).length>1?'s':''} pendant ${duration(last)}.`:'Une expédition prête à accueillir tes souvenirs.'}</p><div class="stats"><div class="stat"><strong>${expObs(last.id).length}</strong><span>souvenirs</span></div><div class="stat"><strong>${new Set(expObs(last.id).map(o=>o.speciesId).filter(Boolean)).size}</strong><span>espèces</span></div><div class="stat"><strong>${expObs(last.id).filter(o=>o.photo).length}</strong><span>photos</span></div></div></div></article>`:''}`)}
function discoveries(){const pending=state.observations.filter(o=>!o.speciesId);const done=state.observations.filter(o=>o.speciesId).slice().reverse();return shell(`<div class="topbar"><div><div class="eyebrow">Après la sortie</div><h1>Mes découvertes</h1></div><button class="btn icon secondary" id="addLibrary" aria-label="Ajouter des photos">＋</button></div><p class="muted">Une photo à la fois. Identifie en quelques secondes.</p><div class="section-title"><h2>À identifier</h2><span>${pending.length}</span></div>${pending.length?`<div class="photo-list">${pending.slice().reverse().map(o=>`<article class="card photo-card"><span class="badge">À découvrir</span><img src="${o.photo}" alt="Souvenir"><div class="actions"><button class="btn block small" data-identify="${o.id}">Identifier</button></div></article>`).join('')}</div>`:'<div class="card empty">Tout est identifié. Ton Atlas est à jour.</div>'}<div class="section-title"><h2>Souvenirs identifiés</h2><span>${done.length}</span></div>${done.length?`<div class="photo-list">${done.map(o=>{const s=sp(o.speciesId);return `<article class="card photo-card"><img src="${o.photo||s.img}" alt="${esc(s.name)}"><div class="actions"><b>${esc(s.name)}</b><div class="muted">${fmtDate(o.createdAt)}</div></div></article>`}).join('')}</div>`:'<div class="card empty">Tes espèces identifiées apparaîtront ici.</div>'}`)}
function atlas(){const seen=discovered();return shell(`<div class="topbar"><div><div class="eyebrow">Ta collection vivante</div><h1>Mon Atlas</h1></div><span class="count">${seen.size}/${species.length}</span></div><div class="notice">Chaque espèce confirmée rejoint ton Atlas et utilise en priorité ta propre photo.</div><div class="species-grid">${species.map((s,i)=>`<article class="card species clickable ${seen.has(s.id)?'':'locked'}" data-species="${s.id}"><img src="${seen.has(s.id)?imageForSpecies(s.id):s.img}" alt="${esc(s.name)}"><div class="species-body"><small>#${String(i+1).padStart(3,'0')}</small><h3>${seen.has(s.id)?esc(s.name):'Espèce à découvrir'}</h3><small>${seen.has(s.id)?esc(s.latin):esc(s.habitat)}</small></div></article>`).join('')}</div>`)}
function journal(){const exps=[...state.expeditions].sort((a,b)=>b.startedAt-a.startedAt);return shell(`<div class="topbar"><div><div class="eyebrow">Tes histoires sous-marines</div><h1>Journal</h1></div><span class="count">${exps.length}</span></div>${exps.length?exps.map(e=>{const os=expObs(e.id);const cover=os.find(o=>o.photo)?.photo;const ids=new Set(os.map(o=>o.speciesId).filter(Boolean));return `<article class="card expedition-card clickable" data-open-exp="${e.id}">${cover?`<img class="expedition-cover" src="${cover}" alt="Couverture">`:''}<div class="expedition-body"><div class="eyebrow">${fmtDate(e.startedAt)}</div><h2>${esc(e.title||e.spot||'Expédition')}</h2><p class="mini-story">${os.length?`Tu as exploré ${esc(e.spot||'la Corse-du-Sud')} pendant ${duration(e)} et capturé ${os.length} souvenir${os.length>1?'s':''}.`:'Expédition sans souvenir.'}</p><div class="stats"><div class="stat"><strong>${os.length}</strong><span>souvenirs</span></div><div class="stat"><strong>${ids.size}</strong><span>espèces</span></div><div class="stat"><strong>${os.filter(o=>o.photo).length}</strong><span>photos</span></div></div></div></article>`}).join(''):'<div class="card empty">Commence une expédition pour créer ton premier souvenir.</div>'}`)}
function profile(){return shell(`<div class="topbar"><div><div class="eyebrow">Ton espace</div><h1>Profil</h1></div><button class="version-pill" id="versionBtn">v${VERSION}</button></div><div class="card profile-hero"><div style="display:flex;gap:15px;align-items:center"><div class="profile-avatar">J</div><div><h2 style="margin-bottom:4px">Julien</h2><p class="muted" style="margin:0">Explorateur sous-marin</p></div></div><div class="stats"><div class="stat"><strong>${state.expeditions.length}</strong><span>expéditions</span></div><div class="stat"><strong>${discovered().size}</strong><span>espèces</span></div><div class="stat"><strong>${state.observations.filter(o=>o.photo).length}</strong><span>photos</span></div></div></div><div class="card"><h3>Protéger mes souvenirs</h3><p class="muted">Crée une sauvegarde avant un changement important de version ou d’adresse.</p><button class="btn block" id="exportBtn">Exporter mes données</button><button class="btn block secondary" id="restoreBtn" style="margin-top:10px">Restaurer une sauvegarde</button></div><div class="card"><h3>Application</h3><p>BlueAtlas Alpha <b>v${VERSION}</b></p><p class="muted">Données stockées uniquement sur cet appareil.</p><button class="btn block danger" id="resetBtn">Effacer toutes les données</button></div><div class="version">Chaque observation raconte une histoire.</div>`)}
function terrain(){const e=active();if(!e)return home();const os=expObs(e.id),pending=os.filter(o=>!o.speciesId).length;return `<section class="terrain"><div class="terrain-bg"></div><div class="terrain-ui"><div class="terrain-head"><div><b>${esc(e.spot||'Expédition')}</b><div class="timer" id="timer">${duration(e)}</div></div><div class="terrain-counter">📷 ${os.length} &nbsp; ❓ ${pending}</div></div><div class="terrain-center"><button class="shutter" id="terrainCamera" aria-label="Capturer un souvenir"></button></div><div class="terrain-foot"><div class="left"><button class="btn secondary small" id="terrainLibrary">Photos</button></div><button class="btn danger small" id="finishExp">Terminer</button><div class="right"><button class="btn secondary small" id="leaveTerrain">Accueil</button></div></div></div></section>`}
function versionModal(){modal=`<div class="modal"><div class="sheet"><button class="btn secondary small" data-close>Fermer</button><div class="eyebrow" style="margin-top:16px">BlueAtlas Alpha</div><h1>Version ${VERSION}</h1><p class="muted">Mise à jour graphique Blue Lagoon.</p><div class="card whats-new"><h3>Nouveautés</h3><ul><li>Accueil immersif et navigation translucide.</li><li>Mode Terrain simplifié avec commandes XXL.</li><li>Découvertes davantage centrées sur les photos.</li><li>Atlas sous forme de cartes premium.</li><li>Journal d’expédition plus narratif.</li><li>Cache PWA renouvelé.</li></ul></div><button class="btn block" data-close>Continuer l’exploration</button></div></div>`;state.seenWhatsNew=true;save();render()}
function speciesModal(sid){const s=sp(sid);const os=state.observations.filter(o=>o.speciesId===sid).sort((a,b)=>b.createdAt-a.createdAt);modal=`<div class="modal"><div class="sheet"><button class="btn secondary small" data-close>Fermer</button><img src="${imageForSpecies(sid)}" alt="${esc(s.name)}" style="margin-top:12px"><h1 style="margin-top:16px">${esc(s.name)}</h1><p><i>${esc(s.latin)}</i></p><span class="chip">${esc(s.group)}</span><span class="chip">${esc(s.habitat)}</span><span class="chip">${s.prob}% indicatif</span><p style="margin-top:15px">${esc(s.desc)}</p><h3>Tes rencontres (${os.length})</h3>${os.length?os.map(o=>`<div class="timeline-item">${o.photo?`<img src="${o.photo}">`:''}<div><b>${fmtDate(o.createdAt)}</b><div class="muted">${esc(o.spot||'Corse-du-Sud')}</div></div></div>`).join(''):'<p class="muted">Pas encore observée.</p>'}</div></div>`;render()}
function identifyModal(oid){const o=state.observations.find(x=>x.id===oid);modal=`<div class="modal"><div class="sheet"><button class="btn secondary small" data-close>Fermer</button><img src="${o.photo}" alt="Photo à identifier" style="margin-top:12px"><h2 style="margin-top:16px">Quelle espèce est-ce ?</h2><input class="field" id="speciesSearch" placeholder="Rechercher une espèce"><div id="candidates">${candidateList('')}</div></div></div>`;render();setTimeout(()=>{document.getElementById('speciesSearch')?.focus()},30)}
function candidateList(q){const qq=q.trim().toLowerCase();return species.filter(s=>!qq||[s.name,s.latin,s.group,s.habitat,s.desc].join(' ').toLowerCase().includes(qq)).sort((a,b)=>b.prob-a.prob).map(s=>`<button class="candidate" data-choose-species="${s.id}"><img src="${s.img}"><div class="grow"><b>${esc(s.name)}</b><div class="muted"><i>${esc(s.latin)}</i> · ${s.prob}%</div></div><span>›</span></button>`).join('')}
function expeditionModal(id){const e=state.expeditions.find(x=>x.id===id),os=expObs(id).sort((a,b)=>a.createdAt-b.createdAt);const ids=[...new Set(os.map(o=>o.speciesId).filter(Boolean))];modal=`<div class="modal"><div class="sheet"><button class="btn secondary small" data-close>Fermer</button><h1 style="margin-top:16px">${esc(e.title||e.spot||'Expédition')}</h1><p class="muted">${fmtDate(e.startedAt)} · ${duration(e)}</p><div class="stats"><div class="stat"><strong>${os.length}</strong><span>souvenirs</span></div><div class="stat"><strong>${ids.length}</strong><span>espèces</span></div><div class="stat"><strong>${os.filter(o=>o.photo).length}</strong><span>photos</span></div></div><div class="notice">${os.length?`Tu as exploré ${esc(e.spot||'la Corse-du-Sud')} pendant ${duration(e)} et capturé ${os.length} souvenir${os.length>1?'s':''}.`:'Cette expédition ne contient encore aucun souvenir.'}</div><h3>Chronologie</h3>${os.length?os.map(o=>{const s=o.speciesId?sp(o.speciesId):null;return `<div class="timeline-item">${o.photo?`<img src="${o.photo}">`:''}<div><b>${new Date(o.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · ${s?esc(s.name):'À identifier'}</b><div class="muted">${s?esc(s.latin):'Souvenir capturé sous l’eau'}</div></div></div>`}).join(''):'<p class="muted">Aucune photo.</p>'}</div></div>`;render()}
function render(){const root=document.getElementById('app');root.innerHTML=active()&&state.selectedTab==='terrain'?terrain():({home:home,discoveries,atlas,journal,profile}[state.selectedTab]||home)();bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.selectedTab=b.dataset.tab;save();render()});document.getElementById('versionBtn')?.addEventListener('click',versionModal);document.getElementById('startExp')?.addEventListener('click',()=>{if(!active()){const spot=prompt('Nom du spot','Palombaggia')||'Corse-du-Sud';const id=uid('exp');state.expeditions.push({id,spot,title:spot,startedAt:Date.now(),endedAt:null});state.activeExpeditionId=id}state.selectedTab='terrain';save();render()});document.getElementById('terrainCamera')?.addEventListener('click',()=>document.getElementById('cameraInput').click());document.getElementById('terrainLibrary')?.addEventListener('click',()=>document.getElementById('libraryInput').click());document.getElementById('addLibrary')?.addEventListener('click',()=>document.getElementById('libraryInput').click());document.getElementById('finishExp')?.addEventListener('click',()=>{const e=active();if(e&&confirm('Terminer cette expédition ?')){e.endedAt=Date.now();state.activeExpeditionId=null;state.selectedTab='journal';save();render()}});document.getElementById('leaveTerrain')?.addEventListener('click',()=>{state.selectedTab='home';save();render()});document.querySelectorAll('[data-identify]').forEach(b=>b.onclick=()=>identifyModal(b.dataset.identify));document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>speciesModal(b.dataset.species));document.querySelectorAll('[data-open-exp]').forEach(b=>b.onclick=()=>expeditionModal(b.dataset.openExp));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{modal=null;render()});document.getElementById('speciesSearch')?.addEventListener('input',e=>document.getElementById('candidates').innerHTML=candidateList(e.target.value));document.querySelectorAll('[data-choose-species]').forEach(b=>b.onclick=()=>{const oid=state.observations.find(o=>!o.speciesId&&modal?.includes(o.id))?.id;let obs=oid&&state.observations.find(o=>o.id===oid);if(!obs){const img=document.querySelector('.sheet>img')?.src;obs=state.observations.find(o=>o.photo===img)}if(obs){obs.speciesId=b.dataset.chooseSpecies;obs.certainty='confirmed';save();modal=null;render()}});document.getElementById('exportBtn')?.addEventListener('click',exportData);document.getElementById('restoreBtn')?.addEventListener('click',()=>document.getElementById('restoreInput').click());document.getElementById('resetBtn')?.addEventListener('click',()=>{if(confirm('Effacer définitivement toutes les données BlueAtlas ?')){state=defaultState();save();render()}})}
async function ingest(files){const e=active();if(!e){alert('Démarre une expédition avant de capturer un souvenir.');return}for(const f of files){try{const photo=await compressFile(f);state.observations.push({id:uid('obs'),expeditionId:e.id,photo,speciesId:null,certainty:'pending',spot:e.spot,createdAt:Date.now()})}catch(err){console.error(err);alert('Impossible de traiter une photo.')}}save();render()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`blueatlas-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
document.getElementById('cameraInput').addEventListener('change',e=>{ingest([...e.target.files]);e.target.value='' });document.getElementById('libraryInput').addEventListener('change',e=>{ingest([...e.target.files]);e.target.value='' });document.getElementById('restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.observations||!x.expeditions)throw new Error();state=x;save();render();alert('Sauvegarde restaurée.')}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f);e.target.value=''});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
render();
