'use strict';

const VERSION = '1.5.0';
const KEY = 'blueatlas-alpha-081';
const CACHE_BUST = 'ba-150';

const spots = [
  {id:'palombaggia',name:'Palombaggia',region:'Corse-du-Sud',habitat:'Herbiers et rochers',icon:'🌿',difficulty:'Facile',visibility:'Très bonne',access:'Plage',best:'Matin calme',biomes:['Herbier','Roche'],desc:'Une mosaïque de petits fonds, de rochers et de Posidonie, idéale pour débuter et multiplier les rencontres.',route:'Longer les rochers latéraux puis traverser les lisières d’herbier.',accent:'#2fd8bd'},
  {id:'santa-giulia',name:'Santa Giulia',region:'Corse-du-Sud',habitat:'Sable et herbiers',icon:'🏖️',difficulty:'Très facile',visibility:'Bonne',access:'Plage',best:'Avant 10 h',biomes:['Sable','Herbier'],desc:'Une baie protégée et peu profonde, adaptée aux familles et aux observations sur sable.',route:'Explorer les transitions entre sable clair et plaques de Posidonie.',accent:'#56cfe1'},
  {id:'rondinara',name:'Rondinara',region:'Corse-du-Sud',habitat:'Baie, roche et herbier',icon:'🌊',difficulty:'Facile',visibility:'Bonne',access:'Plage',best:'Mer calme',biomes:['Herbier','Roche','Sable'],desc:'Une baie arrondie qui réunit plusieurs habitats accessibles au masque et au tuba.',route:'Suivre un bord rocheux puis revenir par les herbiers peu profonds.',accent:'#48bfe3'},
  {id:'piantarella',name:'Piantarella',region:'Corse-du-Sud',habitat:'Lagon et pleine eau',icon:'💧',difficulty:'Intermédiaire',visibility:'Excellente',access:'Plage',best:'Sans vent',biomes:['Pleine eau','Sable'],desc:'Des eaux turquoise et ouvertes où le vent et le courant doivent être surveillés.',route:'Rester dans les zones abritées et observer la pleine eau près des reliefs.',accent:'#5390d9'},
  {id:'lavezzi',name:'Îles Lavezzi',region:'Corse-du-Sud',habitat:'Granite et pleine eau',icon:'🪨',difficulty:'Intermédiaire',visibility:'Excellente',access:'Bateau',best:'Matin',biomes:['Roche','Pleine eau'],desc:'Un décor granitique emblématique, réputé pour ses eaux claires et ses rencontres plus rares.',route:'Explorer les blocs immergés sans franchir les zones exposées au courant.',accent:'#5e60ce'},
  {id:'campomoro',name:'Campomoro',region:'Corse-du-Sud',habitat:'Rochers et tombants',icon:'🤿',difficulty:'Intermédiaire',visibility:'Très bonne',access:'Plage',best:'Matin',biomes:['Roche','Pleine eau'],desc:'Des reliefs rocheux riches en failles, avec une profondeur qui augmente plus rapidement.',route:'Longer prudemment le relief rocheux en restant proche de la côte.',accent:'#4ea8de'},
  {id:'roccapina',name:'Roccapina',region:'Corse-du-Sud',habitat:'Sable et roche',icon:'☀️',difficulty:'Facile',visibility:'Bonne',access:'Plage',best:'Faible houle',biomes:['Sable','Roche'],desc:'Un paysage spectaculaire mêlant grande plage sableuse et extrémités rocheuses.',route:'Privilégier les deux extrémités rocheuses lorsque la houle est faible.',accent:'#64dfdf'},
  {id:'other',name:'Autre spot',region:'Corse',habitat:'À préciser',icon:'📍',difficulty:'À évaluer',visibility:'Variable',access:'Variable',best:'Selon conditions',biomes:['Herbier','Roche','Sable','Pleine eau'],desc:'Crée une expédition libre et précise ensuite le lieu dans ton journal.',route:'Observe les conditions et reste dans une zone adaptée à ton niveau.',accent:'#22d7df'}
];

const species = [
  {id:'saupe',name:'Saupe',latin:'Sarpa salpa',group:'Poisson',habitat:'Herbier / roche',biome:'Herbier',prob:95,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Sarpa_salpa_1.jpg/640px-Sarpa_salpa_1.jpg',desc:'Poisson argenté parcouru de fines lignes dorées, souvent en banc près des herbiers.',similar:['oblade','sar']},
  {id:'girelle',name:'Girelle commune',latin:'Coris julis',group:'Poisson',habitat:'Roche / herbier',biome:'Herbier',prob:95,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Coris_julis_male.jpg/640px-Coris_julis_male.jpg',desc:'Petite girelle très vive, aux couleurs variables selon le sexe et l’âge.',similar:['serran','castagnole']},
  {id:'sar',name:'Sar commun',latin:'Diplodus sargus',group:'Poisson',habitat:'Roche',biome:'Roche',prob:90,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Diplodus_sargus.jpg/640px-Diplodus_sargus.jpg',desc:'Poisson argenté à bandes sombres, fréquent sur les petits fonds rocheux.',similar:['oblade','saupe']},
  {id:'oblade',name:'Oblade',latin:'Oblada melanura',group:'Poisson',habitat:'Pleine eau / roche',biome:'Pleine eau',prob:85,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Oblada_melanura.jpg/640px-Oblada_melanura.jpg',desc:'Poisson argenté reconnaissable à sa tache noire cerclée de blanc près de la queue.',similar:['sar','saupe']},
  {id:'castagnole',name:'Castagnole',latin:'Chromis chromis',group:'Poisson',habitat:'Roche / pleine eau',biome:'Pleine eau',prob:80,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Chromis_chromis_2.jpg/640px-Chromis_chromis_2.jpg',desc:'Petit poisson sombre nageant en groupes au-dessus des fonds rocheux.',similar:['girelle','serran']},
  {id:'serran',name:'Serran écriture',latin:'Serranus scriba',group:'Poisson',habitat:'Roche / herbier',biome:'Roche',prob:75,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Serranus_scriba.jpg/640px-Serranus_scriba.jpg',desc:'Poisson territorial coloré, avec des motifs bleus et bruns très caractéristiques.',similar:['girelle','mero']},
  {id:'rouget',name:'Rouget de roche',latin:'Mullus surmuletus',group:'Poisson',habitat:'Sable / roche',biome:'Sable',prob:65,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Mullus_surmuletus.jpg/640px-Mullus_surmuletus.jpg',desc:'Explore le fond avec ses deux barbillons sensoriels.',similar:['sar','serran']},
  {id:'poulpe',name:'Poulpe commun',latin:'Octopus vulgaris',group:'Céphalopode',habitat:'Roche',biome:'Roche',prob:35,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Octopus_vulgaris_2.jpg/640px-Octopus_vulgaris_2.jpg',desc:'Maître du camouflage, souvent caché dans une cavité entourée de coquilles.',similar:['seiche']},
  {id:'murene',name:'Murène méditerranéenne',latin:'Muraena helena',group:'Poisson',habitat:'Faille rocheuse',biome:'Roche',prob:25,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Muraena_helena_1.jpg/640px-Muraena_helena_1.jpg',desc:'Poisson allongé vivant dans les failles. Observer à distance sans approcher les mains.',similar:['mero','serran']},
  {id:'seiche',name:'Seiche commune',latin:'Sepia officinalis',group:'Céphalopode',habitat:'Sable / herbier',biome:'Sable',prob:20,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Sepia_officinalis_%28aquarium%29.jpg/640px-Sepia_officinalis_%28aquarium%29.jpg',desc:'Céphalopode capable de changer rapidement de couleur et de texture.',similar:['poulpe']},
  {id:'mero',name:'Mérou brun',latin:'Epinephelus marginatus',group:'Poisson',habitat:'Roche / grotte',biome:'Roche',prob:12,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Epinephelus_marginatus_1.jpg/640px-Epinephelus_marginatus_1.jpg',desc:'Grand poisson emblématique, plus facile à observer dans les zones protégées.',similar:['serran','murene']},
  {id:'barracuda',name:'Barracuda méditerranéen',latin:'Sphyraena viridensis',group:'Poisson',habitat:'Pleine eau',biome:'Pleine eau',prob:10,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Sphyraena_viridensis.jpg/640px-Sphyraena_viridensis.jpg',desc:'Prédateur fuselé parfois visible en banc dans les eaux claires.',similar:['oblade']},
  {id:'oursin',name:'Oursin violet',latin:'Paracentrotus lividus',group:'Échinoderme',habitat:'Roche / herbier',biome:'Herbier',prob:90,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Paracentrotus_lividus_01.jpg/640px-Paracentrotus_lividus_01.jpg',desc:'Oursin fréquent sur les rochers. Ne pas marcher dessus et ne pas le prélever.',similar:['etoile','concombre']},
  {id:'etoile',name:'Étoile de mer rouge',latin:'Echinaster sepositus',group:'Échinoderme',habitat:'Roche',biome:'Roche',prob:20,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Echinaster_sepositus_1.jpg/640px-Echinaster_sepositus_1.jpg',desc:'Étoile rouge vif observée sur les roches ombragées.',similar:['oursin','concombre']},
  {id:'concombre',name:'Concombre de mer noir',latin:'Holothuria forskali',group:'Échinoderme',habitat:'Roche / sable',biome:'Sable',prob:50,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Holothuria_forskali.jpg/640px-Holothuria_forskali.jpg',desc:'Animal benthique allongé participant au recyclage des sédiments.',similar:['oursin','etoile']},
  {id:'crabe',name:'Crabe marbré',latin:'Pachygrapsus marmoratus',group:'Crustacé',habitat:'Rochers superficiels',biome:'Roche',prob:55,img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pachygrapsus_marmoratus_2009_G1.jpg/640px-Pachygrapsus_marmoratus_2009_G1.jpg',desc:'Crabe rapide des rochers battus par les vagues, visible tout près de la surface.',similar:['oursin']}
];

const defaultState = () => ({version:VERSION,expeditions:[],observations:[],activeExpeditionId:null,selectedTab:'home',seenWhatsNew:false,region:'Corse',atlasFilter:'all',atlasBiome:'all',atlasSort:'prob',atlasSearch:'',favoriteSpecies:[],favoriteSpots:[]});
let state = load();
let modal = null;
let currentIdentifyId = null;
let currentCandidateId = null;

function load(){
  try{
    const x=JSON.parse(localStorage.getItem(KEY));
    if(x&&Array.isArray(x.observations)){
      x.expeditions=Array.isArray(x.expeditions)?x.expeditions:[];
      x.selectedTab=x.selectedTab||'home';
      x.seenWhatsNew=Boolean(x.seenWhatsNew);
      x.region=x.region||'Corse';
      x.atlasFilter=x.atlasFilter||'all';
      x.atlasBiome=x.atlasBiome||'all';
      x.atlasSort=x.atlasSort||'prob';
      x.atlasSearch=x.atlasSearch||'';
      x.favoriteSpecies=Array.isArray(x.favoriteSpecies)?x.favoriteSpecies:[];
      x.favoriteSpots=Array.isArray(x.favoriteSpots)?x.favoriteSpots:[];
      return x;
    }
  }catch(e){console.warn('BlueAtlas storage',e)}
  return defaultState();
}
function save(){state.version=VERSION;localStorage.setItem(KEY,JSON.stringify(state))}
function uid(p='id'){return p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(x){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}
function fmtDay(x){return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(x))}
function duration(exp){const end=exp.endedAt||Date.now();const min=Math.max(0,Math.round((end-exp.startedAt)/60000));return min<60?min+' min':Math.floor(min/60)+' h '+String(min%60).padStart(2,'0')}
function sp(id){return species.find(s=>s.id===id)}
function spotById(id){return spots.find(s=>s.id===id)}
function spotExpeditions(spot){return state.expeditions.filter(e=>e.spot===spot.name)}
function spotObservations(spot){const ids=new Set(spotExpeditions(spot).map(e=>e.id));return state.observations.filter(o=>ids.has(o.expeditionId))}
function probableForSpot(spot){const weights={Herbier:{Herbier:18,Roche:5,Sable:3,'Pleine eau':2},Roche:{Roche:18,Herbier:5,Sable:2,'Pleine eau':5},Sable:{Sable:18,Herbier:4,Roche:3,'Pleine eau':2},'Pleine eau':{'Pleine eau':18,Roche:5,Herbier:2,Sable:1}};return species.map(s=>{const bonus=Math.max(...spot.biomes.map(b=>weights[b]?.[s.biome]||0));return {...s,spotScore:Math.min(99,s.prob+bonus)}}).sort((a,b)=>b.spotScore-a.spotScore)}
function startExpeditionFromSpot(spot){let name=spot.name;if(spot.id==='other')name=prompt('Nom du spot','Plage de Corse')||'Corse';const id=uid('exp');state.expeditions.push({id,spot:name,spotId:spot.id,region:spot.region,title:null,startedAt:Date.now(),endedAt:null});state.activeExpeditionId=id;state.selectedTab='terrain';modal=null;save();render()}

function expObs(id){return state.observations.filter(o=>o.expeditionId===id)}
function discovered(){return new Set(state.observations.filter(o=>o.speciesId&&o.certainty!=='pending').map(o=>o.speciesId))}
function active(){return state.expeditions.find(e=>e.id===state.activeExpeditionId&&!e.endedAt)}
function imageForSpecies(sid){const own=[...state.observations].reverse().find(o=>o.speciesId===sid&&o.photo);return own?.photo||sp(sid)?.img||''}
function obsForSpecies(sid){return state.observations.filter(o=>o.speciesId===sid).sort((a,b)=>a.createdAt-b.createdAt)}
function biomeStats(){const seen=discovered();return ['Herbier','Roche','Sable','Pleine eau'].map(name=>{const all=species.filter(s=>s.biome===name);const count=all.filter(s=>seen.has(s.id)).length;return {name,count,total:all.length,pct:all.length?Math.round(count/all.length*100):0,icon:{Herbier:'🌿',Roche:'🪨',Sable:'🏖️','Pleine eau':'🌊'}[name]}})}
function rarity(s){if(s.prob<=15)return {label:'Exceptionnelle',cls:'legendary'};if(s.prob<=30)return {label:'Rare',cls:'rare'};if(s.prob<=60)return {label:'Peu commune',cls:'uncommon'};return {label:'Commune',cls:'common'}}
function lastObsTime(id){const os=obsForSpecies(id);return os.length?os[os.length-1].createdAt:0}
function atlasGoal(){const bs=biomeStats().filter(b=>b.count<b.total).sort((a,b)=>(a.total-a.count)-(b.total-b.count))[0];if(!bs)return 'Tous les écosystèmes pilotes sont complétés.';const left=bs.total-bs.count;return `Plus que ${left} espèce${left>1?'s':''} pour compléter ${bs.name.toLowerCase()}.`}
function collectionDefinitions(){return [
 {id:'herbier',name:'Habitants des herbiers',icon:'🌿',desc:'Les espèces typiques des prairies de Posidonie.',match:s=>s.biome==='Herbier'},
 {id:'roche',name:'Explorateurs des rochers',icon:'🪨',desc:'Poissons et invertébrés des failles et petits tombants.',match:s=>s.biome==='Roche'},
 {id:'sable',name:'Secrets du sable',icon:'🏖️',desc:'Les espèces qui se posent, fouillent ou se camouflent sur le sable.',match:s=>s.biome==='Sable'},
 {id:'pleine-eau',name:'Pleine eau',icon:'🌊',desc:'Les nageurs visibles au-dessus du fond et près de la surface.',match:s=>s.biome==='Pleine eau'},
 {id:'cephalopodes',name:'Céphalopodes',icon:'🐙',desc:'Poulpes, seiches et maîtres du camouflage.',match:s=>s.group==='Céphalopode'},
 {id:'echinodermes',name:'Échinodermes',icon:'⭐',desc:'Oursins, étoiles et concombres de mer.',match:s=>s.group==='Échinoderme'},
 {id:'crustaces',name:'Crustacés',icon:'🦀',desc:'Crabes et autres habitants articulés du littoral.',match:s=>s.group==='Crustacé'},
 {id:'rares',name:'Rencontres rares',icon:'◇',desc:'Les espèces dont la probabilité indicative est inférieure ou égale à 30 %.',match:s=>s.prob<=30}
]}
function collectionStats(){const seen=discovered();return collectionDefinitions().map(c=>{const all=species.filter(c.match),found=all.filter(s=>seen.has(s.id));const pct=all.length?Math.round(found.length/all.length*100):0;return {...c,all,found,total:all.length,count:found.length,pct,left:Math.max(0,all.length-found.length)}})}
function explorerLevel(){const n=discovered().size;if(n>=14)return {title:'Naturaliste des lagons',level:5};if(n>=10)return {title:'Explorateur confirmé',level:4};if(n>=6)return {title:'Observateur curieux',level:3};if(n>=3)return {title:'Apprenti naturaliste',level:2};return {title:'Premier plongeon',level:1}}
function nextCollectionTarget(){return collectionStats().filter(c=>c.left>0&&c.total>0).sort((a,b)=>a.left-b.left||b.pct-a.pct)[0]||null}
function expeditionTitle(e){const os=expObs(e.id), ids=[...new Set(os.map(o=>o.speciesId).filter(Boolean))];const rare=ids.map(sp).filter(Boolean).sort((a,b)=>a.prob-b.prob)[0];const hour=new Date(e.startedAt).getHours();if(rare&&rare.prob<=25)return `La rencontre avec ${rare.name}`;if(hour<9)return `Lumière du matin à ${e.spot}`;if(os.length>=12)return `Grande exploration à ${e.spot}`;return `Les eaux de ${e.spot}`}
function expeditionSpecies(e){return [...new Set(expObs(e.id).map(o=>o.speciesId).filter(Boolean))]}
function newSpeciesForExpedition(e){const before=new Set(state.observations.filter(o=>o.createdAt<e.startedAt&&o.speciesId&&o.certainty!=='pending').map(o=>o.speciesId));return expeditionSpecies(e).filter(id=>!before.has(id))}
function expeditionHighlights(e){const os=expObs(e.id).filter(o=>o.speciesId), ids=expeditionSpecies(e), fresh=newSpeciesForExpedition(e), rare=ids.map(sp).filter(Boolean).sort((a,b)=>a.prob-b.prob)[0];const fav=state.observations.find(o=>o.id===e.favoriteObservationId)||os.find(o=>o.photo)||null;const result=[];if(fresh.length){const s=sp(fresh[0]);if(s)result.push({icon:'✨',label:'Nouvelle découverte',value:s.name,obs:os.find(o=>o.speciesId===s.id)})}if(rare)result.push({icon:'◇',label:'Rencontre la plus rare',value:rare.name,obs:os.find(o=>o.speciesId===rare.id)});if(fav){const s=sp(fav.speciesId);result.push({icon:'★',label:'Photo de couverture',value:s?s.name:'Souvenir sous-marin',obs:fav})}return result.slice(0,3)}
function expeditionStory(e){const os=expObs(e.id), ids=expeditionSpecies(e), fresh=newSpeciesForExpedition(e);const pending=os.filter(o=>!o.speciesId).length;const rare=ids.map(sp).filter(Boolean).sort((a,b)=>a.prob-b.prob)[0];const hour=new Date(e.startedAt).getHours();const moment=hour<9?'au lever du jour':hour<13?'dans la lumière du matin':hour<18?'au fil de l’après-midi':'en fin de journée';let text=`${moment[0].toUpperCase()+moment.slice(1)}, tu as exploré ${esc(e.spot||'la Corse')} pendant ${duration(e)} et capturé ${os.length} souvenir${os.length>1?'s':''}. `;if(ids.length)text+=`Ton récit rassemble ${ids.length} espèce${ids.length>1?'s différentes':' différente'}. `;if(fresh.length)text+=`${fresh.length} nouvelle${fresh.length>1?'s espèces rejoignent':' espèce rejoint'} ton Atlas. `;if(rare)text+=`La rencontre la plus singulière fut ${esc(rare.name)}. `;if(pending)text+=`${pending} photo${pending>1?'s restent':' reste'} encore à identifier.`;return text}

async function compressFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1280;let w=img.width,h=img.height;if(Math.max(w,h)>max){const q=max/Math.max(w,h);w=Math.round(w*q);h=Math.round(h*q)}const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.78))};img.src=r.result};r.readAsDataURL(file)})}

function nav(){return `<nav class="nav">${[['home','⌂','Accueil'],['discoveries','⌁','Explorer'],['atlas','◫','Atlas'],['journal','◇','Journal'],['profile','◎','Profil']].map(([id,ic,l])=>`<button data-tab="${id}" class="${state.selectedTab===id?'active':''}"><b>${ic}</b>${l}</button>`).join('')}</nav>`}
function shell(content){return `<main class="app">${content}</main>${nav()}${modal||''}`}

function home(){
  const d=discovered(), photos=state.observations.filter(o=>o.photo).length, pending=state.observations.filter(o=>!o.speciesId).length;
  const last=[...state.expeditions].filter(e=>e.endedAt).sort((a,b)=>b.startedAt-a.startedAt)[0];
  const running=active();
  return shell(`<section class="hero">
    <div class="brand-row"><div class="brand">BLUE<span>ATLAS</span></div><button class="version-pill" id="versionBtn">Alpha v${VERSION}</button></div>
    <div class="hero-location"><span>📍</span><div><b>${running?esc(running.spot):'Corse-du-Sud'}</b><small>${running?'Expédition en cours':'Prêt pour une nouvelle aventure'}</small></div></div>
    <div class="eyebrow">Compagnon d’exploration</div><h1>${running?'Ton expédition continue':'Bonjour Julien'}</h1>
    <p class="sub">${running?'Retourne au mode terrain en un geste.':'La mer est magnifique aujourd’hui. Capture maintenant, identifie plus tard.'}</p>
    <button class="btn block" id="startExp">${running?'Continuer l’expédition':'Commencer une expédition'}</button>
  </section>
  <div class="stats"><div class="stat"><strong>${d.size}</strong><span>espèces</span></div><div class="stat"><strong>${photos}</strong><span>photos</span></div><div class="stat"><strong>${state.expeditions.length}</strong><span>expéditions</span></div></div>
  ${pending?`<article class="card clickable discovery-callout" data-tab="discoveries"><div class="callout-icon">❓</div><div><div class="eyebrow">À faire après la sortie</div><h2>${pending} souvenir${pending>1?'s':''} à identifier</h2><p class="muted">Retrouve tes photos et complète ton Atlas tranquillement.</p></div><span class="chevron">›</span></article>`:''}
  ${last?`<div class="section-title"><h2>Dernière aventure</h2><span>Revivre</span></div>${expeditionCard(last)}`:''}
  ${(()=>{const c=nextCollectionTarget();return c?`<div class="section-title"><h2>Objectif du moment</h2><span>${c.pct}%</span></div><article class="card clickable home-collection" data-collection="${c.id}"><div class="collection-symbol">${c.icon}</div><div class="grow"><div class="eyebrow">Collection</div><h3>${c.name}</h3><p class="muted">Plus que ${c.left} espèce${c.left>1?'s':''} à découvrir.</p><div class="progress"><i style="width:${c.pct}%"></i></div></div><span class="chevron">›</span></article>`:''})()}
  <div class="section-title"><h2>Préparer une sortie</h2><span>7 spots</span></div><article class="card clickable spot-home-card" data-open-spots><div class="spot-home-map"><i></i><i></i><i></i><i></i></div><div class="grow"><div class="eyebrow">Guide des spots</div><h3>Où explorer aujourd’hui ?</h3><p class="muted">Habitats, difficulté et espèces probables.</p></div><span class="chevron">›</span></article>` )
}

function expeditionCard(e){const os=expObs(e.id),cover=os.find(o=>o.photo)?.photo,ids=new Set(os.map(o=>o.speciesId).filter(Boolean));return `<article class="card expedition-card clickable" data-open-exp="${e.id}">${cover?`<img class="expedition-cover" src="${cover}" alt="Couverture de l’expédition">`:`<div class="expedition-placeholder">🌊</div>`}<div class="expedition-body"><div class="eyebrow">${fmtDay(e.startedAt)}</div><h2>${esc(e.title||expeditionTitle(e))}</h2><p class="mini-story">${expeditionStory(e)}</p><div class="stats"><div class="stat"><strong>${os.length}</strong><span>souvenirs</span></div><div class="stat"><strong>${ids.size}</strong><span>espèces</span></div><div class="stat"><strong>${duration(e)}</strong><span>durée</span></div></div></div></article>`}

function discoveries(){
  const pending=state.observations.filter(o=>!o.speciesId).slice().sort((a,b)=>a.createdAt-b.createdAt);
  const confirmed=state.observations.filter(o=>o.speciesId&&o.certainty==='confirmed');
  const probable=state.observations.filter(o=>o.speciesId&&o.certainty==='probable');
  const review=state.observations.filter(o=>o.certainty==='review');
  const first=pending[0];
  return shell(`<div class="topbar"><div><div class="eyebrow">Capture maintenant. Identifie plus tard.</div><h1>Mes découvertes</h1></div><button class="btn icon secondary" id="addLibrary" aria-label="Ajouter des photos">＋</button></div>
  <div class="discovery-summary card"><div><strong>${pending.length}</strong><span>à identifier</span></div><div><strong>${confirmed.length}</strong><span>confirmées</span></div><div><strong>${probable.length}</strong><span>probables</span></div><div><strong>${review.length}</strong><span>à revoir</span></div></div>
  ${first?`<article class="discovery-focus"><img src="${first.photo}" alt="Découverte à identifier"><div class="focus-gradient"></div><div class="focus-top"><span class="badge">1 sur ${pending.length}</span><span>${esc(first.spot||'Corse')}</span></div><div class="focus-bottom"><div><div class="eyebrow">Prête à être identifiée</div><h2>Qu’as-tu découvert ?</h2><p>${fmtDate(first.createdAt)}</p></div><button class="btn" data-identify="${first.id}">Identifier</button></div></article>`:'<div class="card empty celebration"><b>Tout est identifié ✨</b><br>Ton Atlas est à jour.</div>'}
  ${pending.length>1?`<div class="section-title"><h2>À suivre</h2><span>${pending.length-1}</span></div><div class="discovery-strip">${pending.slice(1).map((o,i)=>`<button data-identify="${o.id}"><img src="${o.photo}" alt="Découverte ${i+2}"><span>${i+2}</span></button>`).join('')}</div>`:''}
  <div class="section-title"><h2>Dernières identifications</h2><span>${confirmed.length+probable.length}</span></div>
  ${confirmed.length+probable.length?`<div class="photo-list">${state.observations.filter(o=>o.speciesId).slice().reverse().slice(0,12).map(o=>{const s=sp(o.speciesId);return `<article class="card photo-card clickable" data-species="${s.id}"><img src="${o.photo||s.img}" alt="${esc(s.name)}"><span class="certainty-dot ${o.certainty}"></span><div class="actions"><b>${esc(s.name)}</b><div class="muted">${o.certainty==='probable'?'Probable':'Confirmée'} · ${fmtDate(o.createdAt)}</div></div></article>`}).join('')}</div>`:'<div class="card empty">Tes espèces identifiées apparaîtront ici.</div>'}`)
}

function reefScene(){const seen=[...discovered()].map(sp).filter(Boolean).slice(0,10);return `<div class="reef"><div class="sun-rays"></div><div class="reef-ground"><span>〰</span><span>⌇</span><span>〰</span></div>${seen.map((s,i)=>`<button class="reef-fish fish-${i%6}" data-species="${s.id}" title="${esc(s.name)}"><img src="${imageForSpecies(s.id)}" alt="${esc(s.name)}"></button>`).join('')}${!seen.length?'<div class="reef-empty">Ton écosystème prendra vie<br>avec chaque découverte.</div>':''}</div>`}

function atlas(){
  const seen=discovered(), biomes=biomeStats();
  const q=(state.atlasSearch||'').trim().toLowerCase();
  let list=species.filter(s=>{
    if(state.atlasFilter==='seen'&&!seen.has(s.id))return false;
    if(state.atlasFilter==='unseen'&&seen.has(s.id))return false;
    if(state.atlasFilter==='favorite'&&!state.favoriteSpecies.includes(s.id))return false;
    if(state.atlasBiome!=='all'&&s.biome!==state.atlasBiome)return false;
    return !q||[s.name,s.latin,s.group,s.habitat,s.desc].join(' ').toLowerCase().includes(q);
  });
  list.sort((a,b)=>state.atlasSort==='name'?a.name.localeCompare(b.name,'fr'):state.atlasSort==='rare'?a.prob-b.prob:state.atlasSort==='recent'?lastObsTime(b.id)-lastObsTime(a.id):b.prob-a.prob);
  return shell(`<div class="topbar"><div><div class="eyebrow">Ta collection vivante</div><h1>Mon Atlas</h1></div><span class="count">${seen.size}/${species.length}</span></div>
  ${reefScene()}
  <article class="card atlas-goal"><div class="goal-icon">🧭</div><div><div class="eyebrow">Prochain objectif</div><b>${atlasGoal()}</b></div></article>
  <div class="section-title"><h2>Écosystèmes</h2><span>Progression</span></div>
  <div class="biome-grid">${biomes.map(b=>`<button class="card biome-card ${state.atlasBiome===b.name?'selected':''}" data-atlas-biome="${b.name}"><div class="biome-icon">${b.icon}</div><div><b>${b.name}</b><small>${b.count}/${b.total} espèces</small></div><div class="progress"><i style="width:${b.pct}%"></i></div><strong>${b.pct}%</strong></button>`).join('')}</div>
  <div class="section-title"><h2>Collections</h2><span>${collectionStats().filter(c=>c.pct===100).length}/${collectionStats().length} complétées</span></div><div class="collection-grid">${collectionStats().map(c=>`<button class="collection-card card" data-collection="${c.id}"><div class="collection-top"><span class="collection-symbol">${c.icon}</span><span class="collection-percent">${c.pct}%</span></div><h3>${c.name}</h3><p>${c.count}/${c.total} espèces</p><div class="collection-ring" style="--pct:${c.pct}"><span>${c.left?c.left:'✓'}</span></div></button>`).join('')}</div>
  <div class="atlas-tools card"><input class="field" id="atlasSearch" value="${esc(state.atlasSearch)}" placeholder="Rechercher une espèce, un habitat…"><div class="filter-row">${[['all','Toutes'],['seen','Découvertes'],['unseen','À découvrir'],['favorite','Favorites']].map(([id,l])=>`<button class="filter-chip ${state.atlasFilter===id?'active':''}" data-atlas-filter="${id}">${l}</button>`).join('')}</div><div class="sort-row"><button class="filter-chip ${state.atlasBiome==='all'?'active':''}" data-atlas-biome="all">Tous les milieux</button><select class="field compact" id="atlasSort"><option value="prob" ${state.atlasSort==='prob'?'selected':''}>Plus probables</option><option value="rare" ${state.atlasSort==='rare'?'selected':''}>Plus rares</option><option value="recent" ${state.atlasSort==='recent'?'selected':''}>Observées récemment</option><option value="name" ${state.atlasSort==='name'?'selected':''}>Nom A–Z</option></select></div></div>
  <div class="section-title"><h2>Cartes d’espèces</h2><span>${list.length} affichée${list.length>1?'s':''}</span></div>
  ${list.length?`<div class="species-grid premium">${list.map(s=>{const r=rarity(s),isSeen=seen.has(s.id),fav=state.favoriteSpecies.includes(s.id),os=obsForSpecies(s.id);return `<article class="card species premium-card clickable ${isSeen?'':'locked'}" data-species="${s.id}"><div class="species-photo"><img src="${imageForSpecies(s.id)}" alt="${esc(s.name)}"><span class="rarity ${r.cls}">${r.label}</span>${fav?'<span class="favorite-mark">★</span>':''}</div><div class="species-body"><small>${esc(s.biome)} · ${s.prob}% indicatif</small><h3>${esc(s.name)}</h3><small><i>${esc(s.latin)}</i></small><div class="species-meta"><span>${isSeen?`${os.length} rencontre${os.length>1?'s':''}`:'Pas encore rencontrée'}</span><span>${isSeen?'Découverte':'À découvrir'}</span></div></div></article>`}).join('')}</div>`:'<div class="card empty">Aucune espèce ne correspond à ces filtres.</div>'}`)
}

function spotsPage(){
 const favorites=new Set(state.favoriteSpots||[]);
 return shell(`<div class="topbar"><div><div class="eyebrow">Prépare ta prochaine aventure</div><h1>Spots de Corse</h1></div><button class="btn icon secondary" data-tab="home" aria-label="Retour">‹</button></div>
 <div class="spot-map card"><div class="corsica-shape"><button data-open-spot="campomoro" style="--x:24%;--y:66%">●</button><button data-open-spot="roccapina" style="--x:42%;--y:83%">●</button><button data-open-spot="lavezzi" style="--x:77%;--y:91%">●</button><button data-open-spot="piantarella" style="--x:85%;--y:72%">●</button><button data-open-spot="palombaggia" style="--x:79%;--y:48%">●</button><button data-open-spot="santa-giulia" style="--x:80%;--y:60%">●</button><button data-open-spot="rondinara" style="--x:68%;--y:68%">●</button></div><div><div class="eyebrow">Carte schématique</div><h2>Corse-du-Sud</h2><p class="muted">Touche un point pour préparer une expédition.</p></div></div>
 <div class="section-title"><h2>Spots recommandés</h2><span>${spots.length-1}</span></div>
 <div class="spots-list">${spots.filter(s=>s.id!=='other').map(s=>{const exps=spotExpeditions(s),obs=spotObservations(s),fav=favorites.has(s.id),top=probableForSpot(s).slice(0,3);return `<article class="card spot-card clickable" data-open-spot="${s.id}" style="--spot-accent:${s.accent}"><div class="spot-card-head"><div class="spot-icon">${s.icon}</div><div class="grow"><h3>${esc(s.name)}</h3><p>${esc(s.habitat)}</p></div>${fav?'<span class="spot-fav">★</span>':''}</div><div class="spot-tags"><span>${s.difficulty}</span><span>${s.visibility}</span><span>${s.access}</span></div><div class="spot-species-preview">${top.map(x=>`<img src="${imageForSpecies(x.id)}" alt="${esc(x.name)}">`).join('')}<small>${exps.length?`${exps.length} sortie${exps.length>1?'s':''} · ${obs.length} souvenirs`:'Pas encore exploré'}</small></div></article>`}).join('')}</div>`)
}
function spotModal(id){const s=spotById(id);if(!s)return;const probs=probableForSpot(s).slice(0,6),exps=spotExpeditions(s),obs=spotObservations(s),seen=new Set(obs.map(o=>o.speciesId).filter(Boolean)),fav=(state.favoriteSpots||[]).includes(s.id);modal=`<div class="modal"><div class="sheet spot-sheet" style="--spot-accent:${s.accent}"><div class="sheet-actions"><button class="btn secondary small" data-close>Fermer</button><button class="favorite-toggle ${fav?'active':''}" data-favorite-spot="${s.id}">${fav?'★':'☆'}</button></div><div class="spot-hero"><span>${s.icon}</span><div><div class="eyebrow">${esc(s.region)}</div><h1>${esc(s.name)}</h1><p>${esc(s.habitat)}</p></div></div><p class="spot-description">${esc(s.desc)}</p><div class="spot-facts"><div><small>Difficulté</small><b>${s.difficulty}</b></div><div><small>Visibilité</small><b>${s.visibility}</b></div><div><small>Accès</small><b>${s.access}</b></div><div><small>Meilleur moment</small><b>${s.best}</b></div></div><div class="card route-card"><div class="eyebrow">Parcours conseillé</div><p>${esc(s.route)}</p></div><div class="section-title"><h2>Espèces probables</h2><span>Indice local</span></div><div class="spot-probables">${probs.map(x=>`<button data-species="${x.id}"><img src="${imageForSpecies(x.id)}" alt="${esc(x.name)}"><div><b>${esc(x.name)}</b><small>${x.spotScore}% indicatif</small></div>${seen.has(x.id)?'<i>✓</i>':''}</button>`).join('')}</div><div class="spot-history card"><div><strong>${exps.length}</strong><span>expéditions</span></div><div><strong>${obs.length}</strong><span>souvenirs</span></div><div><strong>${seen.size}</strong><span>espèces</span></div></div><button class="btn block" data-start-spot="${s.id}">${active()?'Nouvelle expédition ici':'Commencer à '+esc(s.name)}</button></div></div>`;render()}

function journal(){const exps=[...state.expeditions].sort((a,b)=>b.startedAt-a.startedAt);const groups={};exps.forEach(e=>{const k=new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(e.startedAt));(groups[k]||=[]).push(e)});return shell(`<div class="topbar"><div><div class="eyebrow">Tes histoires sous-marines</div><h1>Journal</h1></div><span class="count">${exps.length}</span></div>${exps.length?Object.entries(groups).map(([month,list])=>`<section class="journal-month"><div class="section-title"><h2>${month[0].toUpperCase()+month.slice(1)}</h2><span>${list.length} expédition${list.length>1?'s':''}</span></div>${list.map(expeditionCard).join('')}</section>`).join(''):'<div class="card empty">Commence une expédition pour créer ton premier souvenir.</div>'}`)}

function profile(){const lvl=explorerLevel(),cols=collectionStats(),done=cols.filter(c=>c.pct===100).length;return shell(`<div class="topbar"><div><div class="eyebrow">Ton espace</div><h1>Profil</h1></div><button class="version-pill" id="versionBtn">v${VERSION}</button></div><div class="card profile-hero"><div style="display:flex;gap:15px;align-items:center"><div class="profile-avatar">J</div><div><h2 style="margin-bottom:4px">Julien</h2><p class="muted" style="margin:0">${lvl.title} · Niveau ${lvl.level}</p></div></div><div class="stats"><div class="stat"><strong>${state.expeditions.length}</strong><span>expéditions</span></div><div class="stat"><strong>${discovered().size}</strong><span>espèces</span></div><div class="stat"><strong>${state.observations.filter(o=>o.photo).length}</strong><span>photos</span></div></div></div><div class="card progress-overview"><div class="section-title"><h2>Ma progression</h2><span>${done}/${cols.length}</span></div><div class="profile-progress-ring" style="--pct:${Math.round(discovered().size/species.length*100)}"><strong>${Math.round(discovered().size/species.length*100)}%</strong><span>Atlas</span></div><div class="profile-collections">${cols.slice(0,4).map(c=>`<button data-collection="${c.id}"><span>${c.icon}</span><div><b>${c.name}</b><small>${c.count}/${c.total}</small></div></button>`).join('')}</div></div><div class="card"><h3>Protéger mes souvenirs</h3><p class="muted">Crée une sauvegarde avant un changement important de version ou d’adresse.</p><button class="btn block" id="exportBtn">Exporter mes données</button><button class="btn block secondary" id="restoreBtn" style="margin-top:10px">Restaurer une sauvegarde</button></div><div class="card"><h3>Application</h3><p>BlueAtlas Alpha <b>v${VERSION}</b></p><p class="muted">Données stockées uniquement sur cet appareil.</p><button class="btn block danger" id="resetBtn">Effacer toutes les données</button></div><div class="version">Chaque observation raconte une histoire.</div>`) }

function terrain(){const e=active();if(!e)return home();const os=expObs(e.id),pending=os.filter(o=>!o.speciesId).length;return `<section class="terrain"><div class="terrain-bg"></div><div class="terrain-ui"><div class="terrain-head"><div><b>${esc(e.spot||'Expédition')}</b><div class="timer" id="timer">${duration(e)}</div></div><div class="terrain-counter">📷 ${os.length} &nbsp; ❓ ${pending}</div></div><div class="terrain-center"><button class="shutter" id="terrainCamera" aria-label="Capturer un souvenir"><span>📷</span></button><div class="capture-label">Capturer un souvenir</div></div><div class="terrain-foot"><button class="btn secondary small" id="terrainLibrary">Photothèque</button><button class="btn danger small" id="finishExp">Terminer</button></div></div></section>`}

function versionModal(){modal=`<div class="modal"><div class="sheet"><button class="btn secondary small" data-close>Fermer</button><div class="eyebrow" style="margin-top:16px">BlueAtlas Alpha</div><h1>Version ${VERSION}</h1><p class="muted">Sprint Spots & Exploration.</p><div class="card whats-new"><h3>Nouveautés</h3><ul><li>Guide de sept spots de Corse-du-Sud.</li><li>Carte schématique interactive.</li><li>Difficulté, accès, visibilité et parcours conseillé.</li><li>Espèces probables calculées selon les habitats.</li><li>Historique personnel pour chaque spot.</li><li>Démarrage d’une expédition depuis la fiche du lieu.</li></ul></div><button class="btn block" data-close>Continuer l’exploration</button></div></div>`;state.seenWhatsNew=true;save();render()}
function startExpeditionModal(){modal=`<div class="modal"><div class="sheet"><button class="btn secondary small" data-close>Annuler</button><div class="eyebrow" style="margin-top:16px">Nouvelle aventure</div><h1>Où explores-tu ?</h1><p class="muted">Le spot sera associé automatiquement à toutes les photos de cette expédition.</p><button class="text-action" data-open-spots>Consulter le guide détaillé des spots →</button><div class="spot-grid">${spots.map(s=>`<button class="spot-choice" data-spot="${s.id}"><span>${s.icon}</span><div><b>${esc(s.name)}</b><small>${esc(s.habitat)} · ${s.difficulty}</small></div><i>›</i></button>`).join('')}</div></div></div>`;render()}

function speciesModal(sid){const s=sp(sid),os=obsForSpecies(sid),first=os[0],last=os[os.length-1],fav=state.favoriteSpecies.includes(sid),r=rarity(s);modal=`<div class="modal"><div class="sheet"><div class="sheet-actions"><button class="btn secondary small" data-close>Fermer</button><button class="favorite-toggle ${fav?'active':''}" data-favorite-species="${sid}" aria-label="Ajouter aux favorites">${fav?'★':'☆'}</button></div><img src="${imageForSpecies(sid)}" alt="${esc(s.name)}" style="margin-top:12px"><div class="species-title-row"><div><h1 style="margin:16px 0 4px">${esc(s.name)}</h1><p style="margin:0"><i>${esc(s.latin)}</i></p></div><span class="rarity ${r.cls}">${r.label}</span></div><span class="chip">${esc(s.group)}</span><span class="chip">${esc(s.habitat)}</span><span class="chip">${s.prob}% indicatif</span><p style="margin-top:15px">${esc(s.desc)}</p><div class="personal-story"><div><small>Première rencontre</small><b>${first?fmtDate(first.createdAt):'À découvrir'}</b><span>${first?esc(first.spot||'Corse'):'—'}</span></div><div><small>Dernière rencontre</small><b>${last?fmtDate(last.createdAt):'—'}</b><span>${os.length} observation${os.length>1?'s':''}</span></div></div><h3>Espèces ressemblantes</h3><div class="similar-row">${s.similar.map(id=>{const x=sp(id);return x?`<button class="similar" data-species="${x.id}"><img src="${x.img}" alt="${esc(x.name)}"><span>${esc(x.name)}</span></button>`:''}).join('')}</div><h3>Tes rencontres (${os.length})</h3>${os.length?os.slice().reverse().map(o=>`<div class="timeline-item">${o.photo?`<img src="${o.photo}">`:''}<div><b>${fmtDate(o.createdAt)}</b><div class="muted">${esc(o.spot||'Corse-du-Sud')}</div></div></div>`).join(''):'<p class="muted">Pas encore observée.</p>'}</div></div>`;render()}
function collectionModal(id){const c=collectionStats().find(x=>x.id===id);if(!c)return;const seen=discovered();const next=c.all.filter(s=>!seen.has(s.id)).sort((a,b)=>b.prob-a.prob);modal=`<div class="modal"><div class="sheet collection-sheet"><button class="btn secondary small" data-close>Fermer</button><div class="collection-hero"><span>${c.icon}</span><div><div class="eyebrow">Collection naturaliste</div><h1>${c.name}</h1><p>${c.desc}</p></div></div><div class="collection-big-progress"><div class="profile-progress-ring" style="--pct:${c.pct}"><strong>${c.pct}%</strong><span>${c.count}/${c.total}</span></div><div><h2>${c.left?`${c.left} espèce${c.left>1?'s':''} restante${c.left>1?'s':''}`:'Collection complétée ✨'}</h2><p class="muted">Chaque identification confirmée met automatiquement cette collection à jour.</p></div></div><div class="section-title"><h2>Découvertes</h2><span>${c.count}</span></div>${c.found.length?`<div class="mini-species-grid">${c.found.map(s=>`<button data-species="${s.id}"><img src="${imageForSpecies(s.id)}"><span>${s.name}</span></button>`).join('')}</div>`:'<div class="card empty">Aucune espèce de cette collection pour le moment.</div>'}<div class="section-title"><h2>À rechercher</h2><span>${next.length}</span></div>${next.length?`<div class="collection-missing">${next.map(s=>`<button class="candidate" data-species="${s.id}"><img src="${s.img}"><div class="grow"><b>${s.name}</b><div class="muted">${s.habitat} · ${s.prob}% indicatif</div></div><span>›</span></button>`).join('')}</div>`:'<div class="card celebration"><b>Bravo, collection complète !</b><p class="muted">Toutes les espèces pilotes de ce thème sont dans ton Atlas.</p></div>'}</div></div>`;render()}

function identifyModal(oid){
  const o=state.observations.find(x=>x.id===oid);if(!o)return;
  currentIdentifyId=oid;currentCandidateId=null;
  const pending=state.observations.filter(x=>!x.speciesId).sort((a,b)=>a.createdAt-b.createdAt);
  const pos=Math.max(0,pending.findIndex(x=>x.id===oid));
  modal=`<div class="modal identify-workflow"><div class="sheet"><div class="sheet-actions"><button class="btn secondary small" data-close>Fermer</button><span class="workflow-count">${pos+1}/${pending.length}</span></div><div class="identify-photo-wrap"><img src="${o.photo}" alt="Ta photo à identifier" class="identify-user-photo"><span class="photo-label">Ta photo</span></div><div class="eyebrow" style="margin-top:16px">Suggestions prioritaires</div><h2>Quelle espèce reconnais-tu ?</h2><div class="suggestion-grid">${suggestionCards(o)}</div><input class="field" id="speciesSearch" placeholder="Rechercher dans l’Atlas"><div id="candidates" class="candidate-list">${candidateList('',3)}</div><button class="btn secondary block" id="markReview" style="margin-top:12px">Je ne sais pas — à revoir</button></div></div>`;
  render();
}
function rankedSpecies(o){
  const exp=state.expeditions.find(e=>e.id===o.expeditionId);const spot=spots.find(x=>x.name===exp?.spot);
  return species.slice().sort((a,b)=>{let sa=a.prob,sb=b.prob;if(spot){const h=spot.habitat.toLowerCase();if(h.includes(a.biome.toLowerCase().split(' ')[0]))sa+=18;if(h.includes(b.biome.toLowerCase().split(' ')[0]))sb+=18}return sb-sa});
}
function suggestionCards(o){return rankedSpecies(o).slice(0,3).map((s,i)=>`<button class="suggestion-card" data-preview-species="${s.id}"><img src="${s.img}" alt="${esc(s.name)}"><span class="suggestion-rank">${i+1}</span><div><b>${esc(s.name)}</b><small>${s.prob}% indicatif</small></div></button>`).join('')}
function candidateList(q,skip=0){const qq=q.trim().toLowerCase();return species.filter(s=>!qq||[s.name,s.latin,s.group,s.habitat,s.desc].join(' ').toLowerCase().includes(qq)).sort((a,b)=>b.prob-a.prob).slice(skip).map(s=>`<button class="candidate" data-preview-species="${s.id}"><img src="${s.img}"><div class="grow"><b>${esc(s.name)}</b><div class="muted"><i>${esc(s.latin)}</i> · ${s.habitat}</div></div><span>Comparer</span></button>`).join('')}
function compareCandidate(sid){
 const o=state.observations.find(x=>x.id===currentIdentifyId),s=sp(sid);if(!o||!s)return;currentCandidateId=sid;
 modal=`<div class="modal identify-workflow"><div class="sheet"><div class="sheet-actions"><button class="btn secondary small" id="backToCandidates">Retour</button><button class="btn secondary small" data-close>Fermer</button></div><div class="compare-grid"><div><span>Ta photo</span><img src="${o.photo}" alt="Ta photo"></div><div><span>Référence</span><img src="${s.img}" alt="${esc(s.name)}"></div></div><div class="species-title-row"><div><div class="eyebrow">Comparaison</div><h1>${esc(s.name)}</h1><p><i>${esc(s.latin)}</i></p></div><span class="rarity ${rarity(s).cls}">${rarity(s).label}</span></div><p>${esc(s.desc)}</p><div class="quick-details"><label>Profondeur estimée<input class="field" id="obsDepth" inputmode="decimal" placeholder="ex. 2 m" value="${esc(o.depth||'')}"></label><label>Taille estimée<input class="field" id="obsSize" placeholder="ex. 25 cm" value="${esc(o.size||'')}"></label></div><textarea class="field" id="obsNotes" rows="3" placeholder="Une note facultative…">${esc(o.notes||'')}</textarea><div class="validation-actions"><button class="btn block" data-confirm-certainty="confirmed">Oui, c’est elle</button><button class="btn secondary block" data-confirm-certainty="probable">Probablement</button></div></div></div>`;render();
}

function discoveryModal(sid){const s=sp(sid);modal=`<div class="modal discovery-modal"><div class="sheet"><div class="discovery-burst">✨</div><div class="eyebrow">Nouvelle espèce</div><h1>${esc(s.name)}</h1><p><i>${esc(s.latin)}</i></p><img src="${imageForSpecies(sid)}" alt="${esc(s.name)}"><p class="muted">Cette rencontre rejoint maintenant ton Atlas vivant.</p><button class="btn block" data-close>Voir la prochaine découverte</button></div></div>`;render()}

function expeditionModal(id){
 const e=state.expeditions.find(x=>x.id===id);if(!e)return;state.lastOpenedExpeditionId=id;save();
 const os=expObs(id).sort((a,b)=>a.createdAt-b.createdAt),ids=expeditionSpecies(e),fresh=newSpeciesForExpedition(e),pending=os.filter(o=>!o.speciesId),highlights=expeditionHighlights(e);
 const favorite=state.observations.find(o=>o.id===e.favoriteObservationId),cover=favorite?.photo||os.find(o=>o.photo)?.photo;
 const gallery=os.filter(o=>o.photo);
 modal=`<div class="modal"><div class="sheet expedition-sheet"><div class="sheet-actions sticky-actions"><button class="btn secondary small" data-close>Fermer</button><div><button class="btn secondary small" id="editExpTitle">Renommer</button> <button class="btn secondary small" id="shareExp">Partager</button></div></div>${cover?`<div class="journal-cover"><img class="journal-hero" src="${cover}" alt="Couverture"><div class="journal-cover-gradient"></div><div class="journal-cover-copy"><div class="eyebrow">${fmtDay(e.startedAt)}</div><h1>${esc(e.title||expeditionTitle(e))}</h1><p>${esc(e.spot)} · ${duration(e)}</p></div></div>`:`<div class="eyebrow" style="margin-top:16px">${fmtDay(e.startedAt)}</div><h1>${esc(e.title||expeditionTitle(e))}</h1><p class="muted">${esc(e.spot)} · ${duration(e)}</p>`}
 <div class="stats journal-stats"><div class="stat"><strong>${os.length}</strong><span>souvenirs</span></div><div class="stat"><strong>${ids.length}</strong><span>espèces</span></div><div class="stat"><strong>${fresh.length}</strong><span>nouvelles</span></div><div class="stat"><strong>${pending.length}</strong><span>à identifier</span></div></div>
 <div class="journal-story">${expeditionStory(e)}</div>
 ${highlights.length?`<div class="section-title"><h2>Moments forts</h2><span>${highlights.length}</span></div><div class="highlight-grid">${highlights.map(h=>`<article class="highlight-card" ${h.obs?.photo?`data-photo="${h.obs.id}"`:''}><span>${h.icon}</span>${h.obs?.photo?`<img src="${h.obs.photo}" alt="${esc(h.value)}">`:''}<div><small>${h.label}</small><b>${esc(h.value)}</b></div></article>`).join('')}</div>`:''}
 ${gallery.length?`<div class="section-title"><h2>Galerie</h2><span>${gallery.length} photo${gallery.length>1?'s':''}</span></div><div class="journal-gallery">${gallery.map((o,i)=>`<button data-photo="${o.id}" class="gallery-item ${i===0?'wide':''}"><img src="${o.photo}" alt="Souvenir ${i+1}"><span>${new Date(o.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</span></button>`).join('')}</div>`:''}
 <div class="section-title"><h2>Chronologie</h2><span>${os.length}</span></div>${os.length?os.map(o=>{const s=o.speciesId?sp(o.speciesId):null;const fav=e.favoriteObservationId===o.id;return `<div class="timeline-item ${!s?'pending':''}">${o.photo?`<button class="timeline-photo" data-photo="${o.id}"><img src="${o.photo}"></button>`:''}<div class="grow"><b>${new Date(o.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · ${s?esc(s.name):'À identifier'}</b><div class="muted">${s?esc(s.latin):'Souvenir capturé sous l’eau'}</div>${o.notes?`<p class="timeline-note">${esc(o.notes)}</p>`:''}${!s?`<button class="text-action" data-identify="${o.id}">Identifier maintenant</button>`:''}</div>${o.photo?`<button class="favorite-photo ${fav?'active':''}" data-cover-photo="${o.id}" aria-label="Définir comme couverture">${fav?'★':'☆'}</button>`:''}</div>`}).join(''):'<p class="muted">Aucune photo.</p>'}
 </div></div>`;render()
}
function photoModal(oid){const o=state.observations.find(x=>x.id===oid);if(!o?.photo)return;const s=o.speciesId?sp(o.speciesId):null;modal=`<div class="modal photo-viewer"><div class="sheet"><button class="btn secondary small" data-close>Fermer</button><img src="${o.photo}" alt="Souvenir plein écran"><div class="photo-caption"><div><div class="eyebrow">${fmtDate(o.createdAt)}</div><h2>${s?esc(s.name):'Souvenir à identifier'}</h2><p class="muted">${esc(o.spot||'Corse')}</p></div></div></div></div>`;render()}
async function shareExpedition(id){const e=state.expeditions.find(x=>x.id===id);if(!e)return;const os=expObs(id),ids=expeditionSpecies(e);const text=`${e.title||expeditionTitle(e)} — ${e.spot}
${fmtDay(e.startedAt)} · ${duration(e)}
${os.length} souvenirs · ${ids.length} espèces · ${newSpeciesForExpedition(e).length} nouvelles découvertes

Créé avec BlueAtlas.`;try{if(navigator.share)await navigator.share({title:e.title||expeditionTitle(e),text});else{await navigator.clipboard.writeText(text);alert('Résumé copié dans le presse-papiers.')}}catch(err){if(err?.name!=='AbortError')alert('Le partage n’est pas disponible sur cet appareil.')}}

function render(){const root=document.getElementById('app');root.innerHTML=active()&&state.selectedTab==='terrain'?terrain():({home,discoveries,atlas,journal,profile,spots:spotsPage}[state.selectedTab]||home)();bind()}

function bind(){
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.selectedTab=b.dataset.tab;save();render()});
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{modal=null;currentIdentifyId=null;currentCandidateId=null;render()});
  document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>speciesModal(b.dataset.species));
  document.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>collectionModal(b.dataset.collection));
  document.querySelectorAll('[data-open-exp]').forEach(b=>b.onclick=()=>expeditionModal(b.dataset.openExp));
  document.querySelectorAll('[data-open-spots]').forEach(b=>b.onclick=()=>{modal=null;state.selectedTab='spots';save();render()});
  document.querySelectorAll('[data-open-spot]').forEach(b=>b.onclick=()=>spotModal(b.dataset.openSpot));
  document.querySelectorAll('[data-start-spot]').forEach(b=>b.onclick=()=>{const spot=spotById(b.dataset.startSpot);if(spot)startExpeditionFromSpot(spot)});
  document.querySelectorAll('[data-favorite-spot]').forEach(b=>b.onclick=()=>{const id=b.dataset.favoriteSpot;state.favoriteSpots=state.favoriteSpots.includes(id)?state.favoriteSpots.filter(x=>x!==id):[...state.favoriteSpots,id];save();spotModal(id)});

  document.querySelectorAll('[data-identify]').forEach(b=>b.onclick=()=>identifyModal(b.dataset.identify));
  document.querySelectorAll('[data-atlas-filter]').forEach(b=>b.onclick=()=>{state.atlasFilter=b.dataset.atlasFilter;save();render()});
  document.querySelectorAll('[data-atlas-biome]').forEach(b=>b.onclick=()=>{state.atlasBiome=b.dataset.atlasBiome;save();render()});
  document.querySelectorAll('[data-favorite-species]').forEach(b=>b.onclick=()=>{const id=b.dataset.favoriteSpecies;state.favoriteSpecies=state.favoriteSpecies.includes(id)?state.favoriteSpecies.filter(x=>x!==id):[...state.favoriteSpecies,id];save();speciesModal(id)});
  document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>photoModal(b.dataset.photo));
  document.querySelectorAll('[data-cover-photo]').forEach(b=>b.onclick=()=>{const oid=b.dataset.coverPhoto;const o=state.observations.find(x=>x.id===oid),e=o&&state.expeditions.find(x=>x.id===o.expeditionId);if(e){e.favoriteObservationId=e.favoriteObservationId===oid?null:oid;save();expeditionModal(e.id)}});
  document.querySelectorAll('[data-spot]').forEach(b=>b.onclick=()=>{const spot=spotById(b.dataset.spot);if(spot)startExpeditionFromSpot(spot)});
  document.getElementById('shareExp')?.addEventListener('click',()=>{const open=document.querySelector('.expedition-sheet');if(!open)return;const e=[...state.expeditions].sort((a,b)=>b.startedAt-a.startedAt).find(x=>(x.title||expeditionTitle(x))===open.querySelector('h1')?.textContent)||state.expeditions.find(x=>x.id===state.lastOpenedExpeditionId);if(e)shareExpedition(e.id)});
  document.getElementById('editExpTitle')?.addEventListener('click',()=>{const e=state.expeditions.find(x=>x.id===state.lastOpenedExpeditionId);if(!e)return;const title=prompt('Titre de l’expédition',e.title||expeditionTitle(e));if(title!==null){e.title=title.trim()||expeditionTitle(e);save();expeditionModal(e.id)}});
  document.getElementById('versionBtn')?.addEventListener('click',versionModal);
  document.getElementById('startExp')?.addEventListener('click',()=>{if(active()){state.selectedTab='terrain';save();render()}else startExpeditionModal()});
  document.getElementById('terrainCamera')?.addEventListener('click',()=>document.getElementById('cameraInput').click());
  document.getElementById('terrainLibrary')?.addEventListener('click',()=>document.getElementById('libraryInput').click());
  document.getElementById('addLibrary')?.addEventListener('click',()=>{if(!active()){alert('Démarre une expédition avant d’ajouter des photos.');return}document.getElementById('libraryInput').click()});
  document.getElementById('finishExp')?.addEventListener('click',()=>{const e=active();if(e&&confirm('Terminer cette expédition ?')){e.endedAt=Date.now();e.title=expeditionTitle(e);state.activeExpeditionId=null;state.selectedTab='journal';save();expeditionModal(e.id)}});
  document.getElementById('speciesSearch')?.addEventListener('input',e=>{document.getElementById('candidates').innerHTML=candidateList(e.target.value,0);bindCandidates()});
  document.getElementById('atlasSearch')?.addEventListener('input',e=>{state.atlasSearch=e.target.value;save();render()});
  document.getElementById('atlasSort')?.addEventListener('change',e=>{state.atlasSort=e.target.value;save();render()});
  bindCandidates();
  document.getElementById('exportBtn')?.addEventListener('click',exportData);
  document.getElementById('restoreBtn')?.addEventListener('click',()=>document.getElementById('restoreInput').click());
  document.getElementById('resetBtn')?.addEventListener('click',()=>{if(confirm('Effacer définitivement toutes les données BlueAtlas ?')){state=defaultState();save();render()}});
}
function bindCandidates(){
 document.querySelectorAll('[data-preview-species]').forEach(b=>b.onclick=()=>compareCandidate(b.dataset.previewSpecies));
 document.querySelectorAll('[data-confirm-certainty]').forEach(b=>b.onclick=()=>{
   const obs=state.observations.find(o=>o.id===currentIdentifyId);if(!obs||!currentCandidateId)return;
   const wasSeen=discovered().has(currentCandidateId);
   obs.speciesId=currentCandidateId;obs.certainty=b.dataset.confirmCertainty;
   obs.depth=document.getElementById('obsDepth')?.value.trim()||'';obs.size=document.getElementById('obsSize')?.value.trim()||'';obs.notes=document.getElementById('obsNotes')?.value.trim()||'';
   save();const sid=currentCandidateId;currentIdentifyId=null;currentCandidateId=null;
   const next=state.observations.filter(o=>!o.speciesId).sort((a,b)=>a.createdAt-b.createdAt)[0];
   if(!wasSeen&&obs.certainty==='confirmed'){discoveryModal(sid)}else if(next){identifyModal(next.id)}else{modal=null;render()}
 });
 document.getElementById('backToCandidates')?.addEventListener('click',()=>identifyModal(currentIdentifyId));
 document.getElementById('markReview')?.addEventListener('click',()=>{const obs=state.observations.find(o=>o.id===currentIdentifyId);if(!obs)return;obs.certainty='review';save();const next=state.observations.filter(o=>!o.speciesId&&o.id!==obs.id&&o.certainty!=='review').sort((a,b)=>a.createdAt-b.createdAt)[0];currentIdentifyId=null;currentCandidateId=null;if(next)identifyModal(next.id);else{modal=null;render()}});
}

async function ingest(files){const e=active();if(!e){alert('Démarre une expédition avant de capturer un souvenir.');return}for(const f of files){try{const photo=await compressFile(f);state.observations.push({id:uid('obs'),expeditionId:e.id,photo,speciesId:null,certainty:'pending',spot:e.spot,region:e.region||state.region,createdAt:Date.now()})}catch(err){console.error(err);alert('Impossible de traiter une photo.')}}save();render()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`blueatlas-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

document.getElementById('cameraInput').addEventListener('change',e=>{ingest([...e.target.files]);e.target.value='' });
document.getElementById('libraryInput').addEventListener('change',e=>{ingest([...e.target.files]);e.target.value='' });
document.getElementById('restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.observations||!x.expeditions)throw new Error();state=x;save();render();alert('Sauvegarde restaurée.')}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f);e.target.value=''});

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register(`sw.js?v=${CACHE_BUST}`).catch(console.warn))}
if(!state.seenWhatsNew||state.version!==VERSION){state.seenWhatsNew=false;save();setTimeout(versionModal,300)}else render();
